version: '3.4'

services:
  scuffedauth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
  db:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password_123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"