version: '3.4'

services:
  scuffedauth:
    image: ${DOCKER_REGISTRY-}scuffedauth
    build:
      context: .
      dockerfile: ScuffedAuth/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
